# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mindful Design Manifesto
email: ely@mindfuldesign.io
description: my mindfully dynamic manifesto on design as a way of life
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mindfuldesign.github.io" 
twitter_username: creativ_ely
github_username:  elykahn

# Build settings
markdown: kramdown
